### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sagangwee** [jalagar/selfspoken#1]
#### d3 visualization
- [ ] mental state over time (cloudy thing or bar graph?)
#### Site Layout
- [x] set up basic template
- [x] navigation
- [x] text typing box as form to submit to db
- [ ] big mic for audio
- [ ] trends/history page
- [ ] Analysis for spider webs
- [ ] diary page go through past and see data
#### Flask
- [ ] User Login and sessions
- [x] Set up database
- [ ] Communicate diary entries to view
#### Watson API
- [x] tone analysis
- [ ] give summary of thoughts (current mood and maybe suggestion of steps to take)
